import {
  ApplicationCommandRegistries,
  LogLevel,
  RegisterBehavior,
  SapphireClient,
} from "@sapphire/framework";
import { GatewayIntentBits } from "discord.js";
import env from "./utils/env.js";
import { sapphireLogger } from "./utils/log.js";
import { srcDir } from "./utils/workdir.js";
import "@kaname-png/plugin-subcommands-advanced/register";
import { Scheduler } from "./domain/schedules/Scheduler.js";
import { AutoReturnTask } from "./domain/schedules/tasks/AutoReturnTask.js";
import { ReminderTask } from "./domain/schedules/tasks/ReminderTask.js";

// このBOTはGUILD_IDのサーバーのみで動作する (他鯖で動作させない)
ApplicationCommandRegistries.setDefaultGuildIds([env.GUILD_ID]);
// このBotが登録しているコマンドを全置き換えする
ApplicationCommandRegistries.setDefaultBehaviorWhenNotIdentical(
  RegisterBehavior.BulkOverwrite,
);

// Sapphireクライアントの初期化
const client = new SapphireClient({
  logger: {
    level: LogLevel.Debug,
    instance: sapphireLogger,
  },
  shards: "auto",
  intents: [GatewayIntentBits.GuildMessages, GatewayIntentBits.Guilds],
  loadMessageCommandListeners: true,
  baseUserDirectory: srcDir, // TypeScript直読み環境(tsxなど)ではdistではなくsrcディレクトリからコマンドを読み込む
  subcommandsAdvanced: {
    nameCommandsAutogenerated: true, // 同じファイルに複数サブコマンドを定義する場合、名前が被ると読み込まれなくなる問題を回避する
  },
});

// ログイン
try {
  client.logger.info("Logging in");
  await client.login();
  client.logger.info(`Logged in as ${client.user?.tag ?? "Unknown"}`);

  // スケジューラーの初期化と起動（毎日18時に実行）
  const scheduler = new Scheduler(client, "0 18 * * *");
  scheduler.registerTask(new ReminderTask());
  scheduler.registerTask(new AutoReturnTask());
  scheduler.start();
  client.logger.info("Scheduler started");
} catch (error) {
  client.logger.fatal(error);
  await client.destroy();
  process.exit(1);
}
